import 'server-only';
import nodemailer from 'nodemailer';
import type { SubmissionPayload } from '@/types/enquiry';
import { formTypeLabels } from './validations';

const escapeHtml = (value = '') => value.replace(/[&<>'"]/g, (character) => ({
  '&': '&amp;', '<': '&lt;', '>': '&gt;', "'": '&#39;', '"': '&quot;'
}[character] || character));

export async function sendNotificationEmail(payload: SubmissionPayload, submittedAt: Date) {
  const host = process.env.SMTP_HOST;
  const port = Number(process.env.SMTP_PORT || 587);
  const user = process.env.SMTP_USER;
  const password = process.env.SMTP_PASSWORD;
  const recipients = [process.env.NOTIFICATION_EMAIL_1, process.env.NOTIFICATION_EMAIL_2].filter(Boolean) as string[];

  if (!host || !user || !password || recipients.length !== 2) {
    throw new Error('SMTP or notification recipient environment variables are incomplete.');
  }

  const transporter = nodemailer.createTransport({
    host,
    port,
    secure: process.env.SMTP_SECURE === 'true',
    auth: { user, pass: password }
  });

  const rows = [
    ['Form Type', formTypeLabels[payload.formType]],
    ['Name', payload.name],
    ['Email', payload.email],
    ['Phone', payload.phone || '—'],
    ['Company', payload.company || '—'],
    ['Country', payload.country || '—'],
    ['Event', payload.event || '—'],
    ['Subject', payload.subject || '—'],
    ['Message', payload.message || '—'],
    ['Submitted At', submittedAt.toISOString()]
  ];

  const htmlRows = rows.map(([label, value]) => `
    <tr>
      <td style="padding:10px 14px;border-bottom:1px solid #e5e7eb;font-weight:700;width:150px">${escapeHtml(label)}</td>
      <td style="padding:10px 14px;border-bottom:1px solid #e5e7eb">${escapeHtml(value)}</td>
    </tr>`).join('');

  await transporter.sendMail({
    from: `Futurex Website <${user}>`,
    to: recipients.join(','),
    replyTo: payload.email,
    subject: `New Futurex Website Enquiry — ${formTypeLabels[payload.formType]}`,
    html: `
      <div style="font-family:Arial,sans-serif;background:#f3f4f6;padding:32px;color:#111827">
        <div style="max-width:720px;margin:0 auto;background:#ffffff;border-top:5px solid #e3131b">
          <div style="padding:26px 28px 8px"><h1 style="margin:0;font-size:24px">New Futurex Website Enquiry</h1></div>
          <table style="border-collapse:collapse;width:100%;font-size:14px">${htmlRows}</table>
          <div style="padding:20px 28px;color:#6b7280;font-size:12px">Generated by the Futurex website submission pipeline.</div>
        </div>
      </div>`
  });
}
